# ARG GO_VERSION="1.22.5-bookworm"
ARG GO_VERSION="1.21.0-bookworm"

FROM golang:$GO_VERSION

ENV DOCKER_BUILDKIT=1

RUN adduser --disabled-password vscode

WORKDIR /app

RUN apt-get update && export DEBIAN_FRONTEND=noninteractive \
    && apt-get -y install --no-install-recommends \
        fd-find \
        fzf \
        gnupg2 \
        jq \
        yq \
        vim \
        ;

USER vscode